site_name: My Project Docs
theme:
  name: material

nav:
  - Home: index.md
  - Modules:
      - Compiler: modules/compiler.md
      - LLM Training: modules/llm_training.md
      - AI Agents: modules/ai_agents.md
      - Backend: modules/backend.md
site_name: My Docs
