from Compiler_V3.WebCodeGenerator.layout.side_nav import add_side_nav
from Compiler_V3.WebCodeGenerator.layout.footer import add_footer
from Compiler_V3.WebCodeGenerator.layout.header import add_header